# .jazzy.yaml

# General configuration options
module: AtalaPrismSDK
author: IOG
github_url: https://github.com/input-output-hk/atala-prism-wallet-sdk-swift

# Source directory and files to include
#source:
#  - MyLibrary/
#  - README.md

# Markdown files to include
documentation:
  - 'Documentation/*.md'

custom_categories:
  - name: Getting Started
    children:
    - AtalaPrismSDK
    - Mediation
    - Logging
  - name: Architecture
    children:
    - BuildingBlocks
    - TechnicalConsiderations
    - ModularApproach
  - name: Error Handling
    children:
    - ErrorHandling
    - ApolloErrors
    - CastorErrors
    - MercuryErrors
    - PlutoErrors
    - PrismAgentErrors
  - name: Prism Agent
    children:
    - PrismAgent
    - PrismAgentTutorials
  - name: Apollo
    children:
    - Apollo
    - ApolloTutorials
  - name: Castor
    children:
    - Castor
    - CastorTutorials
  - name: Pluto
    children:
    - Pluto
  - name: Pollux
    children:
    - Pollux
