---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: build
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: github.com

      - name: Adding Known Hosts
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: xcodebuild build test -scheme "AtalaPRISMSDK-Package" -destination "platform=iOS Simulator,name=IPhone 14" -resultBundlePath TestResults

      - name: Publish tests results
        uses: kishikawakatsumi/xcresulttool@v1.7.1
        with:
          path: TestResults.xcresult
          token: ${{ secrets.GITHUB_TOKEN }}
          show-code-coverage: true
        if: success() || failure()
