---
name: Release Documentation

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    name: build documentation and release
    runs-on: macos-13
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: github.com

      - name: Adding Known Hosts
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Build Docs
        uses: nick-fields/retry@v2
        with:
          max_attempts: 6
          retry_on: error
          timeout_minutes: 50
          command: xcodebuild docbuild -scheme EdgeAgentSDK -destination "platform=macOS" -derivedDataPath ./doccBuild OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path ./docc --hosting-base-path '/atala-prism-wallet-sdk-swift'"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v1
