---
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  lint:
    name: test
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test
        run: "swift test"
